name: Selenium Tests CI with Behave

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # 1. Kodu çek
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Python ortamını kur
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.5"

      # 3. Gerekli bağımlılıkları yükle
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Selenium için gerekli tarayıcı sürücüsünü kur
      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb

      # 5. Allure CLI'yi indir ve kur
      - name: Install Allure CLI
        run: |
          curl -o allure.tar.gz -L https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.tgz
          tar -xzf allure.tar.gz
          sudo mv allure-2.21.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          rm -f allure.tar.gz # İndirilen Allure tar dosyasini kaldir

      - name: Create directories for Allure results and history
        run: |
          mkdir -p features/reports/allure-results/history
          
      # Step to retrieve previous Allure history from a branch
      - name: Download Allure history from branch
        run: |
          git fetch origin history-branch
          git checkout origin/history-branch -- features/reports/allure-results/history || echo "No previous history found"
          
      - name: Run Behave Tests and generate Allure results
        run: |
          mkdir -p features/reports/allure-results
          behave --tags=@search -f allure_behave.formatter:AllureFormatter -o features/reports/allure-results || true

      - name: Merge previous Allure history
        run: |
          cp -R features/reports/allure-results/history/* features/reports/allure-results/ || echo "No previous history to merge"
      - name: Generate Allure Report
        run: allure generate features/reports/allure-results/ -o features/allure-report --clean

      - name: Upload Allure HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-report
          path: features/allure-report/
          retention-days: 5

      - name: Handle untracked files (move to temp)
        run: |
          mkdir -p temp
          mv features/allure-report/* temp/ || echo "No files to move" 

      - name: Commit and push Allure history to branch
        run: |
          git config pull.rebase false
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"

      - name: Add all changes or stash untracked ones
        run: |
          # Add all changes or stash untracked ones
          git add --all || git stash

      - name: Fetch the latest history branch
        run: |          
          # Fetch the latest history branch
          git fetch origin history-branch

      - name: Checkout the history branch
        run: |           
          # Checkout the history branch
          git checkout history-branch || git checkout -b history-branch
      
      - name: Pull changes and merge allowing unrelated histories
        run: |
          # Pull changes and merge allowing unrelated histories
          git pull origin history-branch --no-edit --allow-unrelated-histories || echo "No changes to pull"
          
      - name: Add the directories to track history and reports
        run: |
          # Add the directories to track history and reports
          git add features/reports/ features/allure-report/ features/reports/allure-results/
          
      - name: Commit the changes if any
        run: |
          # Commit the changes if any
          git commit -m "Update Allure history and report" || echo "No changes to commit"
      
      - name: Push changes back to the branch with force to ensure sync
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          echo "*.deb" >> .gitignore
          git push origin history-branch --force
          
  test_execution:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        # 8. Allure raporlarını GitHub Actions artefaktı olarak yükle
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-report
          path: features/allure-report

      - name: Deploy Allure report to a separate branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./features/allure-report
          publish_branch: gh-pages
          force_orphan: true
